In [21]:
import pandas as pd
pd.set_option('display.max_columns', None)


df = pd.read_csv('dataset/Chicago_Crimes.csv')
df

/var/folders/89/6kh1d12d6wb1vmr80tys6q6h0000gn/T/ipykernel_23826/2112362334.py:5: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('dataset/Chicago_Crimes.csv')

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,13311263,JG503434,07/29/2022 03:39:00 AM,023XX S TROY ST,1582,OFFENSE INVOLVING CHILDREN,CHILD PORNOGRAPHY,RESIDENCE,True,False,1033,10.0,25.0,30.0,17,NaN,NaN,2022,04/18/2024 03:40:59 PM,NaN,NaN,NaN
1,13053066,JG103252,01/03/2023 04:44:00 PM,039XX W WASHINGTON BLVD,2017,NARCOTICS,MANUFACTURE / DELIVER - CRACK,SIDEWALK,True,False,1122,11.0,28.0,26.0,18,NaN,NaN,2023,01/20/2024 03:41:12 PM,NaN,NaN,NaN
2,12131221,JD327000,08/10/2020 09:45:00 AM,015XX N DAMEN AVE,0326,ROBBERY,AGGRAVATED VEHICULAR HIJACKING,STREET,True,False,1424,14.0,1.0,24.0,03,1162795.0,1909900.0,2020,05/17/2025 03:40:52 PM,41.908418,-87.677407,"(41.908417822, -87.67740693)"
3,11227634,JB147599,08/26/2017 10:00:00 AM,001XX W RANDOLPH ST,0281,CRIM SEXUAL ASSAULT,NON-AGGRAVATED,HOTEL/MOTEL,False,False,122,1.0,42.0,32.0,02,NaN,NaN,2017,02/11/2018 03:57:41 PM,NaN,NaN,NaN
4,13203321,JG415333,09/06/2023 05:00:00 PM,002XX N Wells st,1320,CRIMINAL DAMAGE,TO VEHICLE,PARKING LOT / GARAGE (NON RESIDENTIAL),False,False,122,1.0,42.0,32.0,14,1174694.0,1901831.0,2023,11/04/2023 03:40:18 PM,41.886018,-87.633938,"(41.886018055, -87.633937881)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8422091,13991734,JJ444423,10/07/2025 09:00:00 PM,010XX N MILWAUKEE AVE,0910,MOTOR VEHICLE THEFT,AUTOMOBILE,STREET,False,False,1213,12.0,27.0,24.0,07,1166630.0,1907361.0,2025,10/15/2025 03:55:37 PM,41.901369,-87.663392,"(41.901369302, -87.663391932)"
8422092,13991229,JJ443785,10/07/2025 10:26:00 PM,079XX S HALSTED ST,0454,BATTERY,"AGGRAVATED P.O. - HANDS, FISTS, FEET, NO / MIN...",PARKING LOT / GARAGE (NON RESIDENTIAL),True,False,621,6.0,17.0,71.0,08B,1172344.0,1852279.0,2025,10/15/2025 03:55:37 PM,41.750095,-87.644027,"(41.750094836, -87.644027249)"
8422093,13996340,JJ449975,09/29/2025 05:20:00 PM,027XX W MONTROSE AVE,0760,BURGLARY,BURGLARY FROM MOTOR VEHICLE,STREET,False,False,1724,17.0,33.0,16.0,06,1157140.0,1929112.0,2025,10/15/2025 03:51:58 PM,41.961254,-87.697657,"(41.961253689, -87.697657333)"
8422094,13990920,JJ443318,10/07/2025 02:56:00 PM,089XX S WALLACE ST,0486,BATTERY,DOMESTIC BATTERY SIMPLE,RESIDENCE,False,True,2223,22.0,21.0,71.0,08B,1173869.0,1845664.0,2025,10/15/2025 03:55:37 PM,41.731909,-87.638635,"(41.731908752, -87.638634675)"
8422095,13990549,JJ442752,10/07/2025 03:30:00 AM,131XX S CARONDOLET AVE,1320,CRIMINAL DAMAGE,TO VEHICLE,STREET,False,False,433,4.0,10.0,55.0,14,1198434.0,1818345.0,2025,10/15/2025 03:55:37 PM,41.656363,-87.549555,"(41.65636344, -87.549555301)"

In [22]:
df.columns

Index(['ID', 'Case Number', 'Date', 'Block', 'IUCR', 'Primary Type',
       'Description', 'Location Description', 'Arrest', 'Domestic', 'Beat',
       'District', 'Ward', 'Community Area', 'FBI Code', 'X Coordinate',
       'Y Coordinate', 'Year', 'Updated On', 'Latitude', 'Longitude',
       'Location'],
      dtype='object')

In [23]:
# Droping location attributes

df.drop(columns=['X Coordinate', 'Y Coordinate', 'Latitude', 
                 'Longitude', 'Location', 
                 'Updated On', 'Date', 'Year', 
                 'ID', 'Case Number', 'Block',], inplace=True)
df

,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,Beat,District,Ward,Community Area,FBI Code
0,1582,OFFENSE INVOLVING CHILDREN,CHILD PORNOGRAPHY,RESIDENCE,True,False,1033,10.0,25.0,30.0,17
1,2017,NARCOTICS,MANUFACTURE / DELIVER - CRACK,SIDEWALK,True,False,1122,11.0,28.0,26.0,18
2,0326,ROBBERY,AGGRAVATED VEHICULAR HIJACKING,STREET,True,False,1424,14.0,1.0,24.0,03
3,0281,CRIM SEXUAL ASSAULT,NON-AGGRAVATED,HOTEL/MOTEL,False,False,122,1.0,42.0,32.0,02
4,1320,CRIMINAL DAMAGE,TO VEHICLE,PARKING LOT / GARAGE (NON RESIDENTIAL),False,False,122,1.0,42.0,32.0,14
...,...,...,...,...,...,...,...,...,...,...,...
8422091,0910,MOTOR VEHICLE THEFT,AUTOMOBILE,STREET,False,False,1213,12.0,27.0,24.0,07
8422092,0454,BATTERY,"AGGRAVATED P.O. - HANDS, FISTS, FEET, NO / MIN...",PARKING LOT / GARAGE (NON RESIDENTIAL),True,False,621,6.0,17.0,71.0,08B
8422093,0760,BURGLARY,BURGLARY FROM MOTOR VEHICLE,STREET,False,False,1724,17.0,33.0,16.0,06
8422094,0486,BATTERY,DOMESTIC BATTERY SIMPLE,RESIDENCE,False,True,2223,22.0,21.0,71.0,08B
8422095,1320,CRIMINAL DAMAGE,TO VEHICLE,STREET,False,False,433,4.0,10.0,55.0,14

In [24]:
print(len(df[df['District'].isnull()]))

47

In [25]:
# Dropping rows with NaNs

df.dropna(inplace=True)
df.isna().sum()

IUCR                    0
Primary Type            0
Description             0
Location Description    0
Arrest                  0
Domestic                0
Beat                    0
District                0
Ward                    0
Community Area          0
FBI Code                0
dtype: int64

In [29]:
df.columns

Index(['IUCR', 'Primary_Type', 'Description', 'Location_Description', 'Arrest',
       'Domestic', 'Beat', 'District', 'Ward', 'Community_Area', 'FBI_Code'],
      dtype='object')

In [ ]:
df.to_csv('dataset/cleaned_data.csv')